### PR TITLE
wrecking ball swings both ways now!

### LINKED ISSUE #213: Make the direction of the wrecking ball swing based on the selected direction, instead of only swinging up or to the right.

### LINKED ISSUE #238: Defenders should not do damage if the attacker is not in the defender's attack range

### PR DESCRIPTION
**Pull request by cegrief**
resolves #213, resolves #238

### CODE REVIEW

**Comment by cegrief** [comment]
question: should the defender "Miss" or should it just not display any damage? currently does the latter.

**Comment by GregoryElliott** [comment]
I think it should just not display any damage

**Comment by GregoryElliott** [comment]
Because the defender never had an opportunity to do any damage, so its like he "missed"

**Comment by armsnyder** [comment]
I agree with Greg

**Comment by cegrief** [comment]
Thats what it does now, so go ahead and merge if everything else looks okay

**Pull request merged**
