### PR TITLE
fixed 3 bugs

### LINKED ISSUE #198: Some tiles are arbitrarily impossible to move to

### LINKED ISSUE #223: Sometimes after a battle, only one of the two units gets a damage number above its head

### LINKED ISSUE #229: Michael jackson can moonwalk THROUGH adjacent units

### PR DESCRIPTION
**Pull request by cegrief**
resolves #198 
resolves #223 
resolves #229

### CODE REVIEW

**Comment by cegrief** [comment]
I cannot for the life of me figure out why #223 is happening. Its very rare, and when debugging everything looks the same. I'll keep trying.

**Comment by armsnyder** [comment]
yo, I looked at the files changed. The only valid changes are to MelodyUnit.cs and Moonwalk.cs. Everything else is either changing whitespace or git lfs tracking files it should not be.

You can modify the .gitattributes to ignore .asset files in the ProjectSettings/ dir

**Comment by cegrief** [comment]
I wanted the whitespace. Your stupid monodevelop switch statements are ugly

**Comment by cegrief** [comment]
untracking those files using lfs doesn't seem to work. Do you have the syntax for ignoring them in the gitattributes file? or should i just be using .gitignore?

**Pull request merged**
