### PR TITLE
Sprites in Battle Scene and Damage Display

### LINKED ISSUE #51: Have attacking / defending sprites appear on the sides during battle
In front of blurred background but not in front of notes obviously

### PR DESCRIPTION
**Pull request by GregoryElliott**
resolves #51, #144

### CODE REVIEW

**Comment by cegrief** [comment]
(i meant the pull request title)

**Comment by armsnyder** [comment]
Ran your branch and noticed some things
• Damage popups aren't appearing for me
• Particle emitters are disabled
• Battle sprites freeze on whichever frame of the animation they are on upon entering the battle.

**Comment by cegrief** [comment]
actually resolves #51, i think this is fine to merge in now

**Comment by cegrief** [comment]
also #144

**Comment by cegrief** [comment]
I'm merging this just so its done with.

**Pull request merged**
