### PR TITLE
76 joystick directions

### LINKED ISSUE #76: Change the vertical control of the joystick and d-pad to be reversed from what it currently is

### LINKED ISSUE #92: Remap attack to Strum+color

### LINKED ISSUE #96: Remap select to tap color

### PR DESCRIPTION
**Pull request by cegrief**
resolves #76, 
resolves #92, 
resolves #96.

Also removes attack interpreter altogether and changes some naming, so someone should make sure i didn't fuck up

### CODE REVIEW

**Comment by cegrief** [comment]
Well I'd appreciate a once over of the changes if you can bear it with all the line endings stuff. I'll take a look at yours

**Comment by armsnyder** [comment]
Gave it a once over and it looked great. Checked out the branch and tested it, and keyboard controls don't work anymore. Can you remap arrow keys to move directions, map asdfg to fret taps without strum, and map spacebar to strum?

We'll have to deal with how to use a keyboard in guitar battles as a special case...

**Comment by cegrief** [comment]
Right Right, on it

**Comment by armsnyder** [comment]
Don't forget left. And up and down also.

**Comment by cegrief** [comment]
Clever... lol. So i am getting an exception when i raise a message. Any idea what might cause this: 

```
Exception while raising message ButtonDownMessage: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.Int32,System.Collections.Generic.List`1[InputButton]].get_Item (Int32 key) [0x000a2] in /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150 
  at BoardInterpreter.OnButtonDown (.ButtonDownMessage m) [0x00157] in D:\Documents\NorthwesternCourses\gamedesign\countermelody\Assets\scripts\interpreter\BoardInterpreter.cs:47 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000d0] in /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000eb] in /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115 
  at Frictionless.MessageRouter.RaiseMessage (System.Object msg) [0x00035] in D:\Documents\NorthwesternCourses\gamedesign\countermelody\Assets\library\Frictionless\MessageRouter.cs:65 
UnityEngine.Debug:LogError(Object)
Frictionless.MessageRouter:RaiseMessage(Object) (at Assets/library/Frictionless/MessageRouter.cs:84)
KeyboardInput:SendButtonPress(InputButton) (at Assets/scripts/input/KeyboardInput.cs:64)
KeyboardInput:Update() (at Assets/scripts/input/KeyboardInput.cs:40)
```

**Comment by cegrief** [comment]
fixed it!

**Comment by armsnyder** [comment]
Hey, so I noticed when I hit space it auto-attacks. Does that mean that you did #93 as well or is this actually a bug?

**Comment by armsnyder** [comment]
Another note - you will never be able to do a non-"smart" attack because hitting any of asdfg sends both a buttonup and a buttondown. Thoughts on sending buttonup on key press and buttonup on key release? Or should we not support advanced attack with keyboard?

**Comment by armsnyder** [comment]
Ok I addressed by previous two comments with a couple commits. Let me know what you think.

**Pull request merged**
