### PR TITLE
Fixed your little problem

### PR DESCRIPTION
**Pull request by nakfoury**
Hi folks,

Take a look at what I've done here. I think this will really help your game.

Thanks,

### CODE REVIEW

**Comment by armsnyder** [comment]
Hello nakfoury,

Thank you for your interest in Countermelody, a rhythm based tactical RPG about battling musicians.

Unfortunately, upon review your code is a little sloppy and could benefit greatly from some comments so that we can better understand what you are trying to do here.

**Comment by nakfoury** [comment]
Dear armsnyder,

Very sorry for the miscommunicattion   BUT am sure that you will look again to see the code provided meets or exceeds your standards for sloppiness. You may see my comment s in the commit logs but i may reiterate blelow:

Remove orange commander solve #30

Thanks again great game

**Comment by armsnyder** [comment]
Dear nakfoury,

While I find your tremendous work here to be a great leap forward for Countermelody, I do not feel personally qualified to merge your pull request without some review from the other Countermelody collaborators. I appreciate your patience and understanding in the matter.

Best regards,
armsnyder

**Comment by nakfoury** [comment]
@cegrief @GregoryElliott I believe this is the developement team you mean to say? I will bring them into the conversatio nhere. 

Looking forward to hear back from all of you

**Comment by cegrief** [comment]
Well, this sure does look right. Did you test it?

**Comment by nakfoury** [comment]
Hello i am sure it is right. I used my own tester system. it si called "code_critic" i write it in emacs thank you

**Comment by nakfoury** [comment]
Best regards
RaShia

**Comment by armsnyder** [comment]
Dear RaShia,

I have tested your branch of the code. It seems as though you have fixed MOVE actions being sent on the beat if the input key is tapped; however, if the player holds the orange fret through the beat, a MOVE message is still sent at the end of the beat window. Please make this fix, and we will be happy to merge in your change.

**Comment by nakfoury** [comment]
See news today

it must work now

**Comment by armsnyder** [comment]
Hello RaShia,

Thank you once again for your contribution. I'm merging your pull request now. You have been a great asset to this project. We look forward to  providing a clean and healthy environment .

**Pull request merged**
