### PR TITLE
cleaned up special move logic and made it nice and modular

### LINKED ISSUE #199: Board highlighting after special move doesn't clear if it's missed

### PR DESCRIPTION
**Pull request by cegrief**
resolves #199 Yay now you can change how long special moves take without magic numbers!

### CODE REVIEW

**Comment by armsnyder** [comment]
So, problem - now there's no way for the move to take less than 5 seconds. If the player is quick and executes the move right away, the game freezes when the move is over until all 5 seconds have elapsed.

**Comment by armsnyder** [comment]
My intuition is you need to store the time when they initiate the special move and check every frame of the coroutine if the time has elapsed instead of yielding 5 seconds up front?

**Comment by cegrief** [comment]
oh that's true isn't it. seems reasonable, brb

**Comment by cegrief** [comment]
any idea why mj's logic is behaving differently

**Comment by cegrief** [comment]
yay it works now

**Comment by armsnyder** [comment]
there's probably a way to make it more efficient using another coroutine instead of checking the clock every tick, but it's not worth trying. this is great.

**Pull request merged**
