### PR TITLE
Units attack in order

### LINKED ISSUE #224: If the attacking unit does enough damage to kill the defending unit, the attacking unit should not take damage

### PR DESCRIPTION
**Pull request by armsnyder**
closes #224

### CODE REVIEW

**Comment by cegrief** [comment]
NO WHY WOULD YOU TAKE THIS FROM ME I HAVE THIS EXACT CHANGE

**Comment by armsnyder** [comment]
YOU ASSIGNED ME TO IT

**Comment by armsnyder** [comment]
I WAS JUST FOLLOWING ORDERS?

**Comment by cegrief** [comment]
oh, i misclicked and took it back :P

**Comment by armsnyder** [comment]
well i got a github email and it was all over

**Comment by armsnyder** [comment]
"ooo! fawkes assigned me something easy! yays!"

**Comment by armsnyder** [comment]
**puuuuuuush**

**Comment by cegrief** [comment]
lolol, works for me. It got done. ez

**Pull request merged**
