### PR TITLE
added more specific unit stats to the prefabs. fixed bug so that black sprite is always on the left in the battle scene. made it so that healing of 0 will not be displayed with + sign on the screen

### PR DESCRIPTION
**Pull request by GregoryElliott**

### CODE REVIEW

**Comment by cegrief** [comment]
Can you add the replenish > 0 logic to the damage one too?
After that this looks good

**Comment by cegrief** [comment]
also it looks like there is a conflict. I'll give a shot at actually merging it once you fix that issue, but if it doesn't work we'll have to figure out which changes to redo.

**Comment by GregoryElliott** [comment]
Added the logic

**Comment by GregoryElliott** [comment]
to Damage Display

**Comment by cegrief** [comment]
I also fixed a bug that units could only heal to 100

**Pull request merged**
