### PR TITLE
both units deal damage after the fight

### LINKED ISSUE #215: Both units involved in battle should take damage

### PR DESCRIPTION
**Pull request by cegrief**
resolves #215, the damage is just calculated straight up based on hit %, so attacker doesn't have an advantage. Can easily tweak

### CODE REVIEW

**Comment by armsnyder** [comment]
lol

**Comment by armsnyder** [comment]
love it

**Comment by cegrief** [comment]
indeed

**Comment by armsnyder** [comment]
Not gonna un-merge BUT there's a change we should make. If the amount of damage done to the defender is enough to kill them, no damage should be done to the attacker.

**Comment by armsnyder** [comment]
(that's the attacker's advantage in other tactical rpgs if we're copying the mechanic)

**Pull request merged**
